expo/expo-github-action

login/Dockerfile
@byCedric,
Thanks a lot for putting efforts in trying to get actions available for the expo-cli. I've been looking at getting those implemented, but lacked the motivation/knowledge to get started.
During my tests of your action, I've been having lots of problems getting a successful and censored login with the expo-cli. I'm sure you are still working on it as I can see that your docker hub has a few recent changes.
I've come to realise that in order to use the SECRETs without them returning 'Filtered', they need to be use by the `entrypoint.sh` directly and not through arguments. I was inspired by the how the docker/login action works.
The login action in this PR seems to work flawlessly in the different tests I've made, even censoring the SECRET correctly.
Let me know what you think! …
=> Add Login Action

LICENSE.md
=> docs: add 650 industries aka expo as license holder

base/Dockerfile
This is related to NPM failing for both iltorb and sharp dependencies. Let's work around this by using Yarn for now.
https://github.com/expo/expo-cli/issues/591
=> fix: use yarn to install expo cli globally

README.md, action.yml, build/index.js, build/system.js, src/index.ts, src/system.ts, tests/index.test.ts, tests/system.test.ts
This automagically patches Linux systems with the [recommendation from Ville](https://github.com/expo/expo-cli/issues/277#issuecomment-452685177).
> I only enabled this fix for Linux. MacOS has no issues at all, and Windows seems to have other difficulties we need to address.
It's related to #20.
=> fix: add patch for watchers limit and enospc error

README.md
GitHub Actions is entering general availability on the 13th of November. That means it will soon be out of beta! 🎊🚀
=> docs: remove beta warning just before general availability

README.md, build/index.js, src/index.ts, tests/index.test.ts
Expo recommends using yarn, so let's use that by default.
=> refactor!: use yarn by default instead of npm

.eslintrc.json, README.md, action.yml, build/index.js, package-lock.json, package.json, src/cache.ts, src/install.ts, src/run.ts, tests/install.test.ts, tests/run.test.ts
This adds a built-in cache using the Cypress fork of [`actions/cache`](https://github.com/actions/cache). I tested it on all environments with node 10, 12 and 13.
=> feat: implement cache using github actions

build/index.js, src/expo.ts, tests/expo.test.ts, tests/install.test.ts, tests/system.test.ts, tests/utils.ts
This should make it more obvious when incorrect credentials are provided.
=> feat: fail when provided credentials are incorrect

.editorconfig, build/index.js, src/cache.ts, tests/cache.test.ts, tests/expo.test.ts, tests/install.test.ts, tests/system.test.ts
Add the missing unit tests to the local and remote caching mechanisms.
=> test: add missing cache unit tests

.circleci/config.yml
This validates if the proposed changes also updated the `/build` directory. It's required when merging to master to not-break the workflows.
=> test: check if build is up to date

build/index.js, src/cache.ts, src/expo.ts, src/index.ts, tests/cache.test.ts, tests/expo.test.ts
Fixes the unhandled promise rejection with a global handler.
See [this run](https://github.com/byCedric/use-expo/pull/263/checks?check_run_id=656061231).
=> fix: remove custom and add global error handling

README.md
Rasing PR to make sure, there is proper spacing between the `:heart: icon and the text`.
=> fix: proper space between icon and text

README.md
n/a
None needed. This one is pretty straightforward. Thanks!
=> Grammar fix and relative README link fix

.prettierrc, README.md, action.yml, build/index.js, src/expo.ts, src/install.ts, src/run.ts, src/system.ts, tests/cache.test.ts, tests/expo.test.ts, tests/run.test.ts, tests/system.test.ts
This implements the `EXPO_TOKEN` authentication method, so you don't have to add `env: EXPO_TOKEN` to every step using expo. Under the hood, it checks if the token is valid by performing `$ expo whoami`.
Blocked by https://github.com/expo/expo-cli/pull/2415
=> feat: add expo token authentication method

package.json, src/cache.ts, tests/cache.test.ts, yarn.lock
#61 
I haven't included any fix for the concurrency issue I mentioned in #61, but it looks like that issue stems from further upstream and isn't necessarily in the scope of this PR anyway. Nevertheless, I'll be keeping an eye on that issue (and maybe proposing a fix for it if I have the time) since it does affect me. If this PR is merged and that issue _does_ get resolved, I'd be happy to make another PR to introduce that fix into this action.
**Edit**: This PR _does_ now include a fix for the above mentioned issue
Feel free to hit me up if you have any questions or concerns. Thanks!
I ran `yarn upgrade` since I noticed a dependabot warning on my fork.
I have not updated the caching section of the README
=> Replace Cypress fork of actions/cache with official @actions/cache package

.eslintrc.js, src/expo.ts, src/install.ts, src/run.ts, tests/run.test.ts
None, but this improves readability of the output. It's grouped by sections instead of dumped in a big list. Outputs like yarn install are hidden under "Installing Expo CLI with yarn" or "Installing Expo CLI from cache or with yarn".
=> refactor: group output by steps for readability

README.md
=> chore: update readme to latest expo cli and node

src/cache.ts, tests/cache.test.ts
Testing your workflow in Github actions might not be the best DX. Having this action work with [nektos/act](https://github.com/nektos/act) would be great to have.
fixes #90
I was looking at detecting if the action is running in the `act` environment, by checking if the `ACT` environment variable is set. But, I assume the cache might not always be available, like on custom runners or enterprise Github users. Instead of checking on the `ACT` env var, I opted to go for improved error handling.
Right now it checks on these two errors:
- If the cache is reserved by a parallel job, using the [`ReserveCacheError`](https://github.com/actions/toolkit/blob/main/packages/cache/src/cache.ts#L152)
- If the error message mentions [`Cache Service Url not …
=> fix: add support for environments without remote cache

tests/cache.test.ts
We don't want leaking annotations for the tests. This mocks `core.warning` to avoid this on irrelevant workflows.
=> chore: mock the github actions warning to avoid leaking annotations

.releaserc.js, README.md, action.yml, src/cache.ts, src/index.ts, src/install.ts, src/run.ts, src/tools.ts, tests/cache.test.ts, tests/install.test.ts, tests/run.test.ts, tests/tools.test.ts
BREAKING CHANGE: Github Action inputs are changed to allow both Expo and EAS CLI.
Part of #97
=> feature!: add support for eas cli installs

CONTRIBUTING.md
#102 
I just happened to be reading through the docs and thought that this should have been updated. If tags are still being set using the `master` branch, feel free to dismiss this PR and close the linked issue. 😄
=> docs: use `main` branch to update `v{major}` tag

README.md
https://github.com/expo/expo-github-action/issues/109
It looks like they still use `master` not `main`. This change resolved my issues. 
https://github.com/unsplash/comment-on-pr
=> Fix Example Code: Point to Different Branch for unsplash/comment-on-pr

README.md
This updates our code to reflect our new domain.
=> update expo.io links to expo.dev

.gitignore, package.json, src/cache.ts, src/run.ts, yarn.lock
This PR bumps the following dev dependencies to the latest version: ESLint, Jest and TypeScript.
Bumping TS also affected the output code so the action rebuild was required, however this should not have any effect on the users.
I have also to add `any` to the errors in try-catch block otherwise lint will complain about `unknown` type. This rule also can be disabled in config, but there were only three occurrences in code, so I have decided to add the missing type.
the last change was an addition of `.idea` directory to the git ignore file.
`yarn lint`, so `tsc` and `eslint` check were successfully when running locally.
`yarn test` did not yield any errors and all 70 tests cases have passed.
=> bump dev dependencies, rebuild action

.github/workflows/ci.yml, .github/workflows/release.yml, README.md
Currently all the examples in Readme and repos own CI workflow uses `setup-node` in the no longer recommended `v1` version.
This PR updates all of the `setup-node` in the repository to the `v2` release. This should not have the effect on the results, but `v2` should be a bit quicker and more secure. Sine it was release almost year ago, the `v2` is also the recommend version of action to use, see:
* https://github.com/actions/setup-node#usage
I have not add the Changelog entry for this change, since it is not directly connected to the Expo action, rather to the general setup of workflows, but if you think it is needed, just let me know. I will updated the PR.
=> update `setup-node` action to `v2` release

.eslintrc.js, src/cache.ts, src/run.ts, tests/run.test.ts, tsconfig.json
Refs:
* #120
As suggested in the referenced PR I have added the `useUnknownInCatchVariables` ignore flag to the TSConfig instead of adding implicit `any`s.
I have also removed all of the disabled ESLint rules and `noImplicitAny` flag from the TSConfig. This resulted in only in one warning in the codebase related to Jest mock, which I was able to fix by mimicking GitHub typing, which used generic.
`yarn lint`, so `tsc` and `eslint` check were successfully.
`yarn test` did not yield any errors.
=> update TSConfig, clean up ESLint rules

.eslintrc.js, .prettierrc, jest.config.js, ncc.js, package.json, src/actions/setup.ts, src/cache.ts, src/tools.ts, tests/actions/setup.test.ts, tests/cache.test.ts, tests/install.test.ts, tests/tools.test.ts, tests/utils.ts, yarn.lock
It looks like despite the presence of `.prettierrc` file, the Prettier check were not hooked up into lint setup or event present in the project dependencies.
This PR adds the missing dependencies, updates the ESLint config to include the Prettier checks and reformats all the files.
I have also extended the scope of the lint check to the project root (because I saw some mixed whitespaces in files at root level), thats also why I have added the `ignorePatterns` entries in the ESLint config, otherwise the check performance has degraded drstically.
=> chore: hook up Prettier, lint root files, reformat

action.yml, package.json, tsconfig.json, yarn.lock
[Node 16 is now available in GHA](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing), let's upgrade to this LTS version.
=> refactor: upgrade to node 16 github actions runtime

.github/workflows/test.yml
This should run the workflow whenever something gets merged to main. It includes a couple of basic e2e validations to make sure the action is in a working state.
=> chore: add basic e2e test workflow for main action

.github/workflows/review.yml
Because we now have e2e tests for macos, ubuntu, and windows, we dont need to lint on this anymore
- Updated build detection based on [GitHub Actions Typescript starter](https://github.com/actions/typescript-action/blob/923e1825864984cabc35c55f4a4f76483f1a3e1f/.github/workflows/check-dist.yml#L39-L53)
=> chore: simplify review and update build detection

README.md, action.yml, build/setup/index.js, src/actions/setup.ts, tests/actions/setup.test.ts
The caches were an experimental feature when added, and required a fork of the `@actions/cache` library. But, the original `@actions/cache` supports it, we can enable this by default. You can still opt-out from using a cache.
=> refactor: enable caches by default

build/preview-comment/index.js, build/setup/index.js, src/expo.ts, src/github.ts, src/worker.ts, tests/github.test.ts, tests/worker.test.ts
Cleans up the code a bit more.
=> refactor: use assert instead of if statements

README.md, preview-comment/README.md
Help people explicitly mention this, avoiding confusion like: #135
=> docs: explicitly add non interactive flag

.github/workflows/test.yml, README.md, build/preview-comment/index.js, preview-comment/README.md, preview-comment/action.yml, src/actions/preview-comment.ts, src/github.ts, tests/actions/preview-comment.test.ts, tests/github.test.ts
This change allows the preview-action to inehrit the token from the current run. It does that by setting a default value for `github-token` to `${{ github.token }}`.
This would make it way easier to set previews up, by not thinking about that token at all. But, it's a bit more "intrusive" compared to the previous way.
=> refactor(preview-comment): auto-fill the github token

.github/workflows/release.yml
On every PR merge or main push, run a test release to preview the expected version
=> chore: always dry run a new release on merge

build/preview-comment/index.js, build/setup/index.js, src/worker.ts, tests/worker.test.ts
Follow-up of #159
This would make stack traces available through Github actions debugging. https://github.com/actions/toolkit/blob/main/docs/action-debugging.md#step-debug-logs
=> fix: output error stacktraces in debug mode

build/preview-comment/index.js, build/setup/index.js, preview-comment/README.md, src/actions/preview-comment.ts, src/expo.ts, tests/expo.test.ts
This PR added a new variable: `projectDeepLink` to support open Expo Go when the user using the Github Mobile app.
=> feat: added projectDeepLink to template variables

README.md
- A bit overkill but there's no real harm in making every reference to the "token" a link to the token generator. I also added a spot where "EXPO_TOKEN" can be <kbd>⌘F</kbd>'d
=> Increase visibility of the EXPO_TOKEN link

.github/workflows/test.yml, build/setup/index.js, src/packager.ts
See #167
This should also add more visibility if something is going wrong on OS or with npm/yarn, like #167.
=> fix: package tool escape path on windows

command/README.md
Fix the wrong commit issue with the solution from https://github.com/actions/checkout/issues/331#issuecomment-925405415
=> fix: update demo workflow to fix checkout issue

preview-comment/README.md
With GH being more restrictive in some repos, always declaring the permission might be better.
=> docs(preview-comment): add missing permissions in examples

README.md
Thanks for `expo-github-action` 🙌 Very useful!
Just a quick PR to upgrade versions in the examples:
- Node.js to v18 (latest LTS)
- `actions/checkout` and `actions/setup-node` to `v3` (latest in their respective docs)
--
--
=> Upgrade versions in examples

README.md, preview-comment/README.md
This fixes the issue with the badge and some other minor fixes.
=> docs: update badge urls in the readmes

package.json
Let's use git to clean out the build files.
=> refactor: drop rimraf dependency

README.md
With the deprecation of `expo publish`, we need to update the examples.
Blocked by #206
=> docs: update the readme with new examples

build/preview-comment/index.js, preview-comment/README.md, src/actions/preview-comment.ts, tests/actions/preview-comment.test.ts
Note, this will be released in v8.
=> refactor(preview-comment)!: deprecate subaction and link to sunsetting blog post

README.md, command/README.md, preview-comment/README.md, preview/README.md
=> docs: update examples for v8

README.md
I tried out the code in the README and got hung up on the fact that EAS CLI was not installed. I was not installed because the README had an example with `expo-version` instead of `eas-version`. This PR updates that key.
=> Updates the example in the README to use eas-version

build/command/index.js, build/fingerprint-post/index.js, build/fingerprint/index.js, build/preview-build/index.js, build/preview-comment/index.js, build/preview/index.js, build/setup/index.js, src/eas.ts, src/expo.ts, src/packager.ts, src/project.ts, src/utils.ts, src/worker.ts, tsconfig.json
=> refactor: update error handling to node 20 standards

build/preview/index.js, src/eas.ts, tests/eas.test.ts
Fixes #251 
Use the same filtering of slugs, as [done in the `expo-dev-client` plugin here](https://github.com/expo/expo/blob/8ae75dde393e5d2393d446227a1fe2482c75eec3/packages/expo-dev-client/plugin/src/getDefaultScheme.ts#L17).
=> fix(preview): filter slugs with special characters to match dev clients `exp+<slug>` scheme
