expo/expo-github-action

- Dockerfile
- LICENSE.md
- README.md
- base/Dockerfile
- base/LICENSE.md
- base/README.md
- build-android/LICENSE.md
- build-android/README.md
- build-ios/LICENSE.md
- build-ios/README.md
- build-web/LICENSE.md
- build-web/README.md
- entrypoint.sh
- login/LICENSE.md
- login/README.md
- publish/LICENSE.md
- publish/README.md
Fixes #2 
All other sub-actions are still here, just to have it backwards compatible. They should not be used.
> Simplify to a single action

- README.md
> docs: update references to action repository

- Dockerfile
> refactor: remove unofficial from the name

- CHANGELOG.md
- Dockerfile
- README.md
This creates a new release for the latest Expo CLI 😄🚀
> Expo CLI v3

- .github/workflows/ci.yml
- node_modules/@actions/core/package.json
- node_modules/@actions/tool-cache/package.json
This should help all future PRs getting validated before merging.
> chore: enable workflow for pull requests

- build/expo.js
- build/system.js
- node_modules/@actions/exec/package.json
- node_modules/bin-links/package.json
- node_modules/gentle-fs/package.json
- node_modules/https-proxy-agent/package.json
- node_modules/npm-normalize-package-bin/package.json
- node_modules/read-cmd-shim/package.json
- src/expo.ts
- src/system.ts
- tests/expo.test.ts
- tests/system.test.ts
This should make the action steps a bit more transparent and could help developers debugging.
> refactor: make logs more visible

- build/index.js
- src/index.ts
- src/run.ts
- tests/expo.test.ts
- tests/install.test.ts
- tests/run.test.ts
This makes the code a bit more predictable, it only self-executes when importing index
> refactor: move index code to run

- action.yml
> docs: update the default packager value in action

- CHANGELOG.md
- package.json
Create the new release `5.1.0`
> chore: release new version 5.1.0

- LICENSE.md
- README.md
Should make it easier to browse through the documentation.
I also want to add a small animation, showing the action and comment with QR code on a PR. That's currently one of the best examples of how this can help in people's workflow.
> docs: refine the readme and update header style

- .eslintrc.js
- build/index.js
- package.json
- yarn.lock
Maintenance update, closes PR #52 as well.
> chore: upgrade all dependencies to latest version

- README.md
Let's show the proper status of the builds.
> docs: update build badge in readme

- .github/workflows/ci.yml
- package.json
- src/cache.ts
- src/expo.ts
- src/install.ts
- src/run.ts
- src/system.ts
- tests/utils.ts
- yarn.lock
> refactor: update all dev dependencies to latest version

- yarn.lock
This bumps up all dependencies to their latest versions.
> chore: update all dependencies to latest versions

- package.json
- tsconfig.json
- yarn.lock
> refactor: simplify typescript config with community config

- .github/workflows/release.yml
- .releaserc.js
- CONTRIBUTING.md
- build/locales1/en.js
- build/locales1/en.json
- build/locales1/es.js
- build/locales1/es.json
- package.json
- yarn.lock
> chore: add semantic release for easy versioning

- .github/workflows/ci.yml
Keeping up with the [latest Node versions](https://nodejs.org/en/about/releases/)
> chore: update node to 14 and 16 in ci

- README.md
Prepare the readme for next release
> docs: update readme for v6 release

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .releaserc.js
> chore: clean up master references in release and workflows

- .github/workflows/test.yml
- build/setup/index.js
- src/worker.ts
- tests/worker.test.ts
Fixes CI to properly authenticate.
> fix: use which instead of npx to authenticate

- build/setup/index.js
- src/actions/setup.ts
Whoops, we don't need to resolve it twice.
> fix: remove double resolving package versions

- build/setup/index.js
- src/packager.ts
- tests/packager.test.ts
#158
This should add more visibility on invalid versions
> fix: improve invalid package version error handling

- README.md
Should help avoid potentially setting invalid versions
> docs: simplify expo cli versioning to latest

- action.yml
- preview-comment/action.yml
> chore: update github action author name

- .github/workflows/review.yml
This should help keeping the pulls as clean as possible
> chore: disallow any linting issues for pulls

- README.md
- command/README.md
- preview-comment/README.md
> docs(command): update readme to fix badge

- .eslintrc.js
- .prettierrc
- CHANGELOG.md
- build/command/index.js
- build/preview-comment/index.js
- build/setup/index.js
- package.json
- src/cacher.ts
- src/expo.ts
- src/packager.ts
- src/utils.ts
- src/worker.ts
- tsconfig.json
- yarn.lock
Just some maintenance to keep all dev dependencies up to date.
> refactor: update dev dependencies

- .github/workflows/test.yml
Just maintainers things ¯\_(ツ)_/¯
> test: make test workflows easier to read

- fingerprint/README.md
fix steps typo inside fingerprint readme
> doc: fix typo for fingerprint readme

- .github/workflows/release.yml
> chore(ci): update release flow with new service account

- .github/workflows/release.yml
- .github/workflows/review.yml
- .github/workflows/test.yml
> chore: update release workflow actions
